name: Build Kernel

on:
  workflow_dispatch:
    inputs:
      debug_enabled:
        type: boolean
        description: 'Run the build with tmate debugging enabled (https://github.com/marketplace/actions/debugging-with-tmate)'     
        required: false
        default: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout kernel source
      uses: actions/checkout@v3
      with:
        repository: degidevops/POCO_X3_NFC-kernel_xiaomi_surya
        ref: richelieu
        fetch-depth: 1

    - name: Setup Env
      run: |
        sudo apt update
        sudo apt-get install -y clang binutils-aarch64-linux-gnu llvm
        make O=out ARCH=arm64 SUBARCH=arm64 surya_defconfig

    - name: Setup Debuge
      uses: mxschmitt/action-tmate@v3
      if: ${{ github.event_name == 'workflow_dispatch' && inputs.debug_enabled }}
    
    - name: Build
      run: |
        echo "degidevops" > .builderdata
        make -j$(nproc --all) CC=clang CROSS_COMPILE=aarch64-linux-gnu- O=out ARCH=arm64 SUBARCH=arm64 LLVM=1 LD=ld.gold

    - name: Upload file
      uses: actions/upload-artifact@v3
      with:
        name: Kernel File
        path: |
          out/arch/arm64/boot/Image.gz
          out/arch/arm64/boot/dtbo.img
          out/arch/arm64/boot/dtb.img
          out/.config
          